Lab_1_GroceryList/mysite/grocery_list/urls.py
from django.urls import path
from . import views


app_name = 'grocery_list'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('add', views.add, name = 'add'),
    path('purchased/<int:id>', views.purchased, name='purchased'),
    path('remove/<int:id>', views.delete, name = 'delete'),
]

Lab_1_GroceryList/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('grocery_list.urls')),
    path('admin/', admin.site.urls),
]

Lab_1_GroceryList/mysite/grocery_list/models.py
import datetime
from django.db import models
from django.utils import timezone

class GroceryItems(models.Model):


    Item_Name = models.CharField(max_length=30)
    Date_Added = models.DateTimeField()
    Purchased = models.BooleanField()
    Date_Purchased = models.DateTimeField(null=True, blank=True)
   

    def __str__(self):
        return self.Item_Name

Lab_1_GroceryList/mysite/grocery_list/views.py
from django.utils import timezone
from django.http.response import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import GroceryItems


def index(request):
    
    grocery_list = GroceryItems.objects.all()
    
    context = {
        'grocery_list': grocery_list,
    }

    return render(request, 'index.html', context)

def add(request):

    New_Item = request.POST['NewItem']
    
    GroceryItems.objects.create(Item_Name=New_Item, Date_Added=timezone.now(), Purchased=False)
    
    return HttpResponseRedirect(reverse('grocery_list:index'))

def purchased(request, id):
    
    Item = get_object_or_404(GroceryItems, pk=id)
    
    Date_Purchased = timezone.now()
    Item.Purchased = True
    Item.Date_Purchased = Date_Purchased
    Item.save()

    return HttpResponseRedirect(reverse('grocery_list:index'))


def delete(request, id):

    Item = get_object_or_404(GroceryItems, pk=id) 
    
    # Item = GroceryItems.objects.get(id=id)
    
    Item.delete()
   
    return HttpResponseRedirect(reverse('grocery_list:index'))

Lab_1_GroceryList/mysite/grocery_list/templates/index.html
<!DOCTYPE html>
<html lang = 'en'>
 
    <head>
        <meta charset = "UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>GROCERY LIST</title>
    </head>

   <body>
        <header>
            
            <h1>Your Grocery List</h1>
          
        </header>
        
        <main>
               
                <ul>

                    {% for Item in grocery_list %}
            
                <li> {{ Item.Item_Name }} 
                        <br>
                        added on {{Item.Date_Added|date:'M d'}}

                        <br><a href="{% url 'grocery_list:purchased' Item.id %}"> <button>purchased</button> </a> 
                        
                        {% if Item.Date_Purchased == None%} 
                        <br> <br><a href="{% url 'grocery_list:delete' Item.id %}"> <button>delete</button> </a>
                        <br> <br>
                        {% else %}
                        on {{Item.Date_Purchased|date:'M d'}} 
                        <br> <br><a href="{% url 'grocery_list:delete' Item.id %}"> <button>delete</button> </a>
                        <br> <br>
                        {% endif %}
                    
                    {% endfor %} 
                </li>
                </ul>

                <form action="{% url 'grocery_list:add' %}" method="post"> 
                {% csrf_token %} 
                <input tpye='text' name='NewItem' value=""></input>
                <button type="submit" name="Submit_Button" value =''> Add</button>
                </form> 
                       
        
        </main>
        <footer>
        </footer>
    
    </body>
</html>