Lab_2_URL/thesite/theapp/urls.py
from django.urls import path
from . import views


app_name = 'theapp'
urlpatterns = [
    path('', views.index, name = 'index'),
    path( '<str:shortcode>', views.redirec, name = 'redirec')
]

Lab_2_URL/thesite/thesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('theapp.urls')),
]

Lab_2_URL/thesite/theapp/models.py
from django.db import models


class Encoder(models.Model):

    url = models.CharField(max_length=30)
    Date_Added = models.DateTimeField(auto_now_add=True, null=True)
    code = models.CharField(max_length=30)
    
   
    def __str__(self):
        return self.url

Lab_2_URL/thesite/theapp/views.py
import random

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect

from .models import Encoder

forcode = ['A','B','C','D','E','F','G','H','1','2','3','4','5']

def index(request):
    
    if request.method=='POST':
        code = list()
        for x in range(5):
            code.append(random.choice(forcode))
        code = ''.join(code)

        encoder = Encoder()
        encoder.url = request.POST['url']
        encoder.code = code
        encoder.save()

        context = {
            'code': code,
            'url': request.POST['url'],
        }
        return render(request, 'index.html', context)
   
    elif request.method=="GET":

        return render(request, 'index.html')

def redirec(request, shortcode):

    url_obj = get_object_or_404(Encoder, code=shortcode)
    aaa = url_obj.url
    bbb = str("Https://www." + aaa )

    return HttpResponseRedirect(bbb)

Lab_2_URL/thesite/theapp/templates/index.html
<!DOCTYPE html>
<html lang = 'en'>
 
    <head>
        <meta charset = "UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>URL ENCODER</title>
    </head>

   <body>
        <header>
            <h1>The URL Encoder</h1>
        </header>
        
        <main>
        <h2>Add the Url you would like to encode</h2>
        <p> Exp: <br>google.com<br> yahoo.com <br> amazon.com</p>
            
            <form action="{% url 'theapp:index' %}" method="post">
                            
            {% csrf_token %}
                
                <input type="text" name="url"></input>
                <button type="submit" value=''> ENCODE</button>
            </form>

        <p> The URL code for " {{url}} " is  ---->  " {{ code }} " . Here is the link <a href="{{code}}"> localhost:8000/{{ code }} </a>  </p>
        
        </main>
        <footer>
        </footer>
    
    </body>
</html>