Lab_3_Chirp/TwitterCopySite/TwitterCopySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('users.urls')),
]

Lab_3_Chirp/TwitterCopySite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts' 
urlpatterns = [
    path('', views.landing, name='landing'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('user/<int:id>',views.profile, name='profile'),
]

Lab_3_Chirp/TwitterCopySite/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
]

Lab_3_Chirp/TwitterCopySite/posts/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime, timedelta
from django.contrib.auth.models import User


class Post(models.Model):
    body = models.CharField(max_length=288)
    time=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(User, on_delete=models.PROTECT, related_name='posts')
    archive = models.BooleanField(default=False)
    archive_date=models.DateTimeField(null=True,blank=True)
    def __str__(self):
        return f'{self.author},{self.time},\n {self.body}'

Lab_3_Chirp/TwitterCopySite/users/models.py
from django.db import models

# Create your models here.

Lab_3_Chirp/TwitterCopySite/posts/views.py
from django.shortcuts import render, get_object_or_404,redirect
from datetime import datetime
from .models import Post, User
from django.template import loader
from django.contrib.auth.decorators import login_required


def landing(request):
    if request.method == 'POST':
        print(request.POST) 
        data = dict(request.POST)
        print(data)
        body=request.POST.get('words')
        Post.objects.create(
			body=body,
			time=datetime.now(),
            author=request.user,
		)
        return redirect('/')

    context={'posts':(Post.objects.all()),}
    print(context)
    return render(request, 'chirp/landing.html', context)

@login_required
def delete(request, id):
    item = get_object_or_404(Post, id=id)
    item.delete()
    return redirect('posts:landing')

@login_required
def profile(request, id):
    if request.method == 'POST':
        print(request.POST) 
        data = dict(request.POST)
        print(data)
        body=request.POST.get('words')
        Post.objects.create(
			body=body,
			time=datetime.now(),
            author=request.user,
		)
        return redirect('/user')
    user=get_object_or_404(User, id=id)
    context={'posts':(Post.objects.filter(author=user.id))}
    return render(request, 'chirp/user.html', context)

Lab_3_Chirp/TwitterCopySite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User


def logout_user(request):
    logout(request)
    return redirect('posts:landing')

def login_user(request):
    if request.method == 'POST':
        print(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('posts:landing')

    return render(request, 'users/login.html')

def register_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 == password2:
            user = User.objects.create_user(
                username=username,
                password=password1
            )
            login(request, user)
            return redirect('posts:landing')

    return render(request, 'users/register.html')

Lab_3_Chirp/TwitterCopySite/posts/templates/chirp/base.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <title>Twitter Copy</title>
            <link  rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
            <link rel="stylesheet" href="/static/style.css">
        </head>
		
		<body>
			<div class="nav">
				<nav>
					{% if user.is_authenticated %}
					<div><a href="/"><strong>Home</strong></a>
						<p> Welcome <a href="{% url 'posts:profile' user.id %}"></a> {{ user.username }} </a> </p>
						<p> <a href="{% url 'users:logout' %}">LOGOUT</a> </p>
					</div>
					{% else %}
					<div>
					<p> <a href="{% url 'users:login' %}">LOGIN</a> </p>
					<p> <a href="{% url 'users:register' %}">SIGNUP</a> </p>
					</div>
					{% endif %}
				</nav>
			</div>
			<div class="header">
					<h2>Post something</h2>   
						<form action="{% url 'posts:landing' %}" method="post">
							{% csrf_token %}
						<input type="text" name="words"/>
						<button type="submit">Post</button>
						</form>
			<div class='posts'>
				{% block content %}
				{% endblock %}	
			</div>
		</body>
	</html>

Lab_3_Chirp/TwitterCopySite/posts/templates/chirp/landing.html
{% extends 'chirp/base.html' %}

    {% block content %}

    {% if user.is_authenticated %}
            <div class='container'>
                {% for post in posts %}  
                    <div class='post'>
                        <h3>{{ post.author }}</h3>
                        <p id="quote">{{ post.body }}</p>
                        <p>{{ post.time }}</p>
                        {% if user.id == post.author.id %}
                            <a href="{% url 'posts:delete' post.id %}"> <button>Delete</button> </a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>    
    {% else %}
    <div class='container'>
        <h1>Please login or singup</h1>
    </div>
    {% endif %}
    
    {% endblock %}

Lab_3_Chirp/TwitterCopySite/posts/templates/chirp/user.html
{% extends 'chirp/base.html' %}

{% block content %}

{% if user.is_authenticated %}

<main>
    <div>
    {% for post in posts %}  
        
    

    <div class='container'>
        {% for post in posts %}  
            <div class='post'>
                <h3>{{ post.author }}</h3>
                <p id="quote">{{ post.body }}</p>
                <p>{{ post.time }}</p>
                {% if user.id == post.author.id %}
                <a href="{% url 'posts:delete' post.id %}">
                    <button>Delete</button>                
                </a>
                {% endif %}
            </div>
    
    {% endfor %}
    </div>
</div>S

    <div>
        <form action="{% url 'posts:landing' %}" method="post">
            {% csrf_token %}
            <input type="text" name="words"/>
            <button type="submit">save</button>
        </form>
    </div>
</main>
{% else %}
<main>
    <h1>Please login or register</h1>
</main>
{% endif %}
{% endblock %}

Lab_3_Chirp/TwitterCopySite/users/templates/users/login.html
<head>
	<style>
		body {
			margin: 3rem;
		}
	</style>
</head>

<h3>login</h3>

<form action="{% url 'users:login' %}" method="POST">
	{% csrf_token %}
	<label for="username">username:</label>
	<input type="text" id="username" name="username">
	<br />
	<label for="password">password:</label>
	<input type="password" id="password" name="password">
	<br />
	<button type="submit">login</button>
</form>

Lab_3_Chirp/TwitterCopySite/users/templates/users/register.html
<head>
	<style>
		body {
			margin: 3rem;
		}
	</style>
</head>

<h3>register</h3>

<form action="{% url 'users:register' %}" method="POST">
	{% csrf_token %}
	<label for="username">username:</label>
	<input type="text" id="username" name="username">
	<br />
	<label for="password"1>password:</label>
	<input type="password" id="password1" name="password1">
	<br />
	<label for="password2">password again:</label>
	<input type="password" id="password2" name="password2">
	<br />
	<button type="submit">login</button>
</form>